INSERT INTO Avaliacoes (LivroID, UsuarioID, Nota, Comentario) VALUES
(1, 1, 5.0, 'Excelente livro com insights valiosos.'),
(10, 2, 4.0, 'Muito bom, recomendo a todos.'),
(12, 3, 3.0, 'Interessante, mas um pouco arrastado.'),
(2, 4, 4.0, 'Gostei bastante, leitura envolvente.'),
(33, 5, 5.0, 'Maravilhoso, superou minhas expectativas.'),
(13, 6, 4.0, 'Bem escrito e cativante.'),
(54, 7, 4.5, 'Uma visão profunda e bem elaborada do futuro.'),
(64, 8, 3.5, 'Bom, mas um pouco previsível.'),
(15, 9, 4.5, 'Aventura fantástica, muito divertido de ler.'),
(85, 10, 4.0, 'História envolvente, personagens bem desenvolvidos.'),
(21, 3, 3.5, 'Bom para uma leitura rápida.'),
(91, 4, 4.5, 'Ótimo livro, cheio de ação e suspense.'),
(32, 5, 4.0, 'Narrativa sólida, bem escrita.'),
(2, 6, 4.5, 'Ótima leitura, história emocionante.'),
(3, 7, 5.0, 'Incrivelmente inspirador e tocante.'),
(3, 8, 4.5, 'Fácil de ler e muito instrutivo.'),
(4, 9, 3.0, 'Interessante, mas não é para todos.'),
(4, 10, 4.5, 'Distopia fascinante, altamente recomendável.'),
(5, 1, 5.0, 'Absolutamente fantástico, uma jornada épica.'),
(5, 2, 3.5, 'Bom, mas esperava mais profundidade.');
